# Generated by Django 5.0 on 2024-03-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=36)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Invoice Amount')),
                ('supplier_reference', models.CharField(max_length=36)),
                ('supplier_company_name', models.CharField(max_length=40)),
                ('supplier_govt_id', models.IntegerField()),
                ('bar_code', models.IntegerField()),
                ('issuer_name', models.CharField(max_length=20)),
            ],
        ),
    ]
